{-# LANGUAGE OverloadedStrings #-}
module Generate.SourceMap
  ( Source(..)
  , extract
  )
  where

-- Turns a JavaScript builder that has been woven with source-map markers
-- (see "Generate.JavaScript.Builder") into a clean JavaScript builder plus a
-- Source Map v3 document. The markers are removed during a single pass over
-- the generated bytes, recording the generated position they appeared at.

import qualified Data.Bits as Bits
import Data.Bits ((.&.), (.|.))
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import qualified Data.ByteString.Lazy as LBS
import qualified Data.ByteString.Unsafe as BSU
import Data.Word (Word8)

import qualified Json.Encode as Json



-- SOURCES


-- One entry per source file, ordered so that the list index matches the
-- source index emitted in the module markers.
data Source =
  Source
    { _path :: FilePath        -- e.g. "src/Main.elm"
    , _content :: BS.ByteString -- the raw UTF-8 source, embedded as sourcesContent
    }



-- EXTRACT


-- | Given the generated file's name, the ordered sources, and the marked
-- JavaScript, produce (cleaned JavaScript, source map JSON).
extract :: String -> [Source] -> B.Builder -> (B.Builder, B.Builder)
extract fileName sources marked =
  let
    bytes = LBS.toStrict (B.toLazyByteString marked)
    (clean, segments) = scan bytes
    mappings = encodeMappings segments
  in
  ( clean
  , Json.encodeUgly $ Json.object
      [ "version" Json.==> Json.int 3
      , "file" Json.==> Json.chars fileName
      , "sourceRoot" Json.==> Json.chars ""
      , "sources" Json.==> Json.array (map (Json.chars . _path) sources)
      , "sourcesContent" Json.==> Json.array (map (jsonBytes . _content) sources)
      , "names" Json.==> Json.array []
      , "mappings" Json.==> jsonAscii mappings
      ]
  )



-- A single mapping segment: genLine genCol srcIndex srcLine srcCol. All values
-- are absolute (0-based, except the source index). Emitted in generated order,
-- so already sorted by (genLine, genCol).
data Segment =
  Segment Int Int Int Int Int



-- SCAN


markerNul :: Word8
markerNul = 0x00


scan :: BS.ByteString -> (B.Builder, [Segment])
scan bytes =
  go 0 0 0 0 Nothing [] []
  where
    len = BS.length bytes

    -- i        : current byte index
    -- runStart : start of the current run of normal (non-marker) bytes
    -- genLine  : current generated line (0-based)
    -- genCol   : current generated column (0-based, counted in code points)
    -- curSrc   : source index the following region markers refer to
    -- revSegs  : segments collected so far, reversed
    -- revChunks: output byte runs collected so far, reversed
    go i runStart genLine genCol curSrc revSegs revChunks
      | i >= len =
          let chunk = slice runStart len in
          ( mconcat (reverse (chunk : revChunks))
          , reverse revSegs
          )
      | b == markerNul =
          let
            chunk = slice runStart i
            chunks = chunk : revChunks
          in
          case BSU.unsafeIndex bytes (i + 1) of
            0x52 {- 'R' -} ->
              let
                (line, j) = readInt (i + 2)
                (col, k)  = readInt (j + 1)      -- skip the ',' at j
                next      = k + 1                -- skip the closing NUL
                segs =
                  case curSrc of
                    Just s  -> Segment genLine genCol s (line - 1) (col - 1) : revSegs
                    Nothing -> revSegs
              in
              go next next genLine genCol curSrc segs chunks

            0x4D {- 'M' -} ->
              let
                (index, j) = readInt (i + 2)
                next       = j + 1               -- skip the closing NUL
              in
              go next next genLine genCol (Just index) revSegs chunks

            _ {- 'N' -} ->
              let next = i + 3 in                -- NUL 'N' NUL
              go next next genLine genCol Nothing revSegs chunks

      | b == 0x0A {- '\n' -} =
          go (i + 1) runStart (genLine + 1) 0 curSrc revSegs revChunks

      | isContinuation b =
          go (i + 1) runStart genLine genCol curSrc revSegs revChunks

      | otherwise =
          go (i + 1) runStart genLine (genCol + 1) curSrc revSegs revChunks
      where
        b = BSU.unsafeIndex bytes i

    slice from to =
      B.byteString (BSU.unsafeTake (to - from) (BSU.unsafeDrop from bytes))

    -- read a run of ASCII decimal digits, returning (value, indexAfterDigits)
    readInt start =
      readIntHelp start 0

    readIntHelp i acc
      | i < len && d >= 0x30 && d <= 0x39 =
          readIntHelp (i + 1) (acc * 10 + fromIntegral (d - 0x30))
      | otherwise =
          (acc, i)
      where
        d = BSU.unsafeIndex bytes i


isContinuation :: Word8 -> Bool
isContinuation b =
  b .&. 0xC0 == 0x80



-- ENCODE MAPPINGS (Base64 VLQ)


encodeMappings :: [Segment] -> B.Builder
encodeMappings segments =
  encodeHelp 0 0 0 0 0 True segments


encodeHelp :: Int -> Int -> Int -> Int -> Int -> Bool -> [Segment] -> B.Builder
encodeHelp prevGenLine prevGenCol prevSrc prevSrcLine prevSrcCol lineStart segments =
  case segments of
    [] ->
      mempty

    Segment gl gc si sl sc : rest ->
      let
        semis = mconcat (replicate (gl - prevGenLine) (B.char7 ';'))
        (baseCol, atStart) =
          if gl > prevGenLine then (0, True) else (prevGenCol, lineStart)
        sep = if atStart then mempty else B.char7 ','
        segment =
          vlq (gc - baseCol)
          <> vlq (si - prevSrc)
          <> vlq (sl - prevSrcLine)
          <> vlq (sc - prevSrcCol)
      in
      semis <> sep <> segment
      <> encodeHelp gl gc si sl sc False rest


vlq :: Int -> B.Builder
vlq n =
  vlqHelp (if n < 0 then (negate n `Bits.shiftL` 1) .|. 1 else n `Bits.shiftL` 1)


vlqHelp :: Int -> B.Builder
vlqHelp value =
  let
    digit = value .&. 31
    rest = value `Bits.shiftR` 5
  in
  if rest > 0
    then B.word8 (base64 (digit .|. 32)) <> vlqHelp rest
    else B.word8 (base64 digit)


base64 :: Int -> Word8
base64 i =
  BSU.unsafeIndex base64Table i


base64Table :: BS.ByteString
base64Table =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"



-- JSON HELPERS


-- | Wrap an all-ASCII builder (safe characters only) as a JSON string.
jsonAscii :: B.Builder -> Json.Value
jsonAscii builder =
  Json.String (B.char7 '"' <> builder <> B.char7 '"')


-- | Encode raw UTF-8 bytes as a JSON string, escaping what JSON requires and
-- passing multibyte sequences through verbatim.
jsonBytes :: BS.ByteString -> Json.Value
jsonBytes bytes =
  Json.String (B.char7 '"' <> BS.foldr (\w acc -> escapeByte w <> acc) mempty bytes <> B.char7 '"')


escapeByte :: Word8 -> B.Builder
escapeByte w =
  case w of
    0x22 -> "\\\""
    0x5C -> "\\\\"
    0x08 -> "\\b"
    0x09 -> "\\t"
    0x0A -> "\\n"
    0x0C -> "\\f"
    0x0D -> "\\r"
    _ | w < 0x20  -> "\\u00" <> hexDigit (w `Bits.shiftR` 4) <> hexDigit (w .&. 0x0F)
      | otherwise -> B.word8 w


hexDigit :: Word8 -> B.Builder
hexDigit w =
  B.word8 (if w < 10 then 0x30 + w else 0x61 + (w - 10))
